### ISSUE TITLE
I'd like to become the maintainer of this Flask-Easy-Template repo

### ISSUE THREAD

**Issue by skorr** [AndreiD/Flask-Easy-Template#5]
Hi Dan (AndreiD), 

I was looking for a Flask starter template, found this and got it running under Python 2.7.5 with more current libraries. This is just the kind of work in progress repo I was looking for.

I've been coding in Python since 2002 and have developed a number of apps with Flask. I've also had recent experience migrating apps from Python 2.x to Python 3.x. 

Please feel free to ask any other questions and let me know what else is to facilitate this transfer.

Thanks,
SKOrr

**Comment by AndreiD** [comment]
sorry now I see this. I've added you :)

**Comment by dbdweeb** [comment]
> sorry now I see this. I've added you :)

Thanks, I guess you're busy just like me. :) 
I've got a work spike at the moment but will participate here next week.
